apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-backup-pv-claim
  labels:
    app: mariadb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: "mariadb-backup-pv-volume"
