apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-backup-pv-volume
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
